/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.cv.gui.cliente;

import br.edu.ifsul.cc.lpoo.cv.Controle;

/**
 *
 * @author phmad
 */
public class JPanelListagem extends javax.swing.JPanel {

    private JPanelCliente painelCliente;
    private Controle controle;
    
    
    public JPanelListagem(JPanelCliente painelCliente, Controle controle) {
        
        this.painelCliente = painelCliente;
        this.controle = controle;
        
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        txtfilNome = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        pnlSul = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTableListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblFiltro.setText("Filtrar por Nome:");
        pnlNorte.add(lblFiltro);

        txtfilNome.setColumns(20);
        txtfilNome.setText("Informe um Nome");
        txtfilNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilNomeActionPerformed(evt);
            }
        });
        pnlNorte.add(txtfilNome);

        jButtonFiltrar.setText("Filtrar");
        pnlNorte.add(jButtonFiltrar);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        jButtonNovo.setBackground(new java.awt.Color(102, 255, 102));
        jButtonNovo.setText("Novo");
        pnlSul.add(jButtonNovo);

        jButtonEditar.setText("Editar");
        pnlSul.add(jButtonEditar);

        jButtonRemover.setBackground(new java.awt.Color(255, 102, 102));
        jButtonRemover.setText("Remover");
        pnlSul.add(jButtonRemover);

        pnlCentro.add(pnlSul, java.awt.BorderLayout.PAGE_END);

        jTableListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Data Ultimo Acesso", "Cidade", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTabela.setViewportView(jTableListagem);

        pnlCentro.add(jScrollPaneTabela, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfilNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTableListagem;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JTextField txtfilNome;
    // End of variables declaration//GEN-END:variables
}
